on: [push]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Dump env
        run: env
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          cache: false
          go-version: "1.20.4"
      - name: Print go cache paths
        run: go env
      - name: Cache setup
        uses: actions/cache@v3
        with:
          path: |-
            .cache/dockercache
          key: ${{ runner.os }}
          restore-keys: ${{ runner.os }}
      - name: Run docker
        run: |-
          docker buildx build --cache-from=type=local,src=$HOME/.cache/dockercache --cache-to=type=local,dest=$HOME/.cache/dockercache -t preprocessor --load -f ./Dockerfile .
